name: Bug Report
description: Report a bug!
title: "[BUG]: "
labels: ["bug", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what should have happened?
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (makes app unusable)
        - Annoying (app still usable, but frustrating)
        - Trivial (something to polish)
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error codes (if any)
      description: Please copy and paste any relevant log output or error codes. This will be auto-formatted; don't put backticks.
      render: shell

