spring:
  application:
    name: emma-server

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emma_data}
    username: ${SPRING_DATASOURCE_USERNAME:emma_su}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_emergency_pwd}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://hewmyprmvhjfpfyjdmpd.supabase.co/auth/v1}
          jwk-set-uri: ${JWK_SET_URI:https://hewmyprmvhjfpfyjdmpd.supabase.co/auth/v1/.well-known/jwks.json}
          jws-algorithms: ES256
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

server:
  forward-headers-strategy: framework

emma:
  cors:
    allowed-origins: "*" # Must be overridden in prod.